{
 "title": "Weather Tracker",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Current Measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", ((temperature_c * 1.8) + 32) AS \"value\" FROM weather_conditions ORDER BY timestamp asc"
    }
   ]
  },
  {
   "title": "Ambient Light",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", light_lumens AS \"value\" FROM weather_conditions ORDER BY \"timestamp\" ASC "
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", altitude_m AS \"value\" FROM weather_conditions ORDER BY \"timestamp\" ASC "
    }
   ]
  },
  {
   "title": "VOC Index",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "VOCs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", voc_index AS \"value\" FROM weather_conditions ORDER BY \"timestamp\" ASC "
    }
   ]
  },
  { "title": "Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", temperature_c AS \"value\" FROM weather_conditions ORDER BY \"timestamp\" ASC "
    }
   ]
  },
  {
   "title": "Gas Resistance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ohm" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", gas_resistance_ohms AS \"value\" FROM weather_conditions ORDER BY \"timestamp\" ASC "
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", pressure_pa AS \"value\" FROM weather_conditions ORDER BY \"timestamp\" ASC "
    }
   ]
  },
  {
   "title": "Dew Point",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", dew_point_c AS \"value\" FROM weather_conditions ORDER BY \"timestamp\" ASC "
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", humidity_rh AS \"value\" FROM weather_conditions ORDER BY \"timestamp\" ASC "
    }
   ]
  }
 ]
}